default['jmeter']['user'] = "root"
default['jmeter']['group'] = "root"
default['jmeter']['version'] = "2.9"
default['jmeter']['root'] = "/usr/local"
default['jmeter']['url'] = "http://ftp.kddilabs.jp/infosystems/apache//jmeter/binaries/apache-jmeter-#{node['jmeter']['version']}.tgz"
default['jmeter']['xms'] = "512m"
default['jmeter']['xmx'] = "512m"
default['jmeter']['server']['port'] = "1099"
